package com.flatcode.littlenotecompose.ui.theme

object Strings {
    const val APP_NAME = "Little Note - Compose"
    const val USERNAME = "Username"
    const val EMAIL_EXAMPLE = "abc@example.com"
    const val NEW_USER_SIGNUP = "New User? SignUp"
    const val FORGET_PASSWORD = "Forget Password?"
    const val ERROR_EMPTY = "Can not Save note with Empty Field."
    const val ERROR_LOG = "Error ! "
    const val TEMPORARY_LOG = "Logged in With Temporary Account."
    const val TEMPORARY_CONNECT = "Your Are Connected."
    const val ALERT_DELETE_TITLE = "Are you sure ?"
    const val ALERT_DELETE_MESSAGE = "You are logged in with Temporary Account. Logging out will Delete All the notes."
    const val ALERT_DELETE_POSITIVE = "Sync Note"
    const val ALERT_DELETE_NEGATIVE = "Logout"
    const val ALERT_LOGIN_MESSAGE = "Linking Existing Account Will delete all the temp notes. Create New Account To Save them."
    const val ALERT_LOGIN_POSITIVE = "Save Notes"
    const val ALERT_LOGIN_NEGATIVE = "Its OK"
    const val EMPTY_REQUIRED = "Fields Are Required."
    const val EMPTY_REQUIRED_ALL = "All Fields Are Required."
    const val ADD_NOTE = "Add Note"
    const val EDIT_NOTE = "Edit Note"
    const val MY_NOTES = "My Notes"
    const val HINT_DESCRIPTION = "Write Your Note Here"
    const val LOGIN = "Login"
    const val PASSWORD = "Password"
    const val EMAIL = "Email"
    const val DESCRIPTION_HERE = "Description Here"
    const val TITLE_HERE = "Title Here"
    const val CD_BACK = "Back"
    const val CD_LOGIN = "Login"
    const val CD_REGISTER = "Register"
    const val CD_ADD = "Add note"
    const val CD_INFO = "Info"
    const val CD_SYNC = "Sync"
    const val CD_LOGOUT = "Logout"
    const val CD_RESET_PASSWORD = "Reset Password"
    const val PASSWORD_HINT = "********"
    const val DO_YOU_WANT_TO_EXIT = "Do you want to Exit ?"
    const val NO = "NO"
    const val YES = "YES"
    const val USER_VISIBLE_DESCRIPTION = "This app allows you to create and manage personal notes using AI agents."
}